#!/usr/bin/env python3
"""Regenerate skills-evidence-matrix.yaml from bullet-library.yaml + publication-library.yaml.
Run from the repo root after editing any skills[] field."""
import yaml

bl = yaml.safe_load(open('bullet-library.yaml'))   # roles -> {meta..., bullets: [...]}, cross-role -> [bullets]
pl = yaml.safe_load(open('publication-library.yaml'))

all_bullets = [b for r in bl.get('roles', {}).values() for b in (r.get('bullets') or [])]
all_bullets += bl.get('cross-role') or []

matrix = {}
for b in all_bullets:
    if not b.get('skills'):
        print(f"WARNING: bullet {b['id']} has no skills[] — it evidences nothing and cannot be traced")
    for s in b.get('skills') or []:
        matrix.setdefault(s, {'bullets': [], 'publications': []})['bullets'].append(b['id'])
for p in pl['publications']:
    for s in p['skills']:
        matrix.setdefault(s, {'bullets': [], 'publications': []})['publications'].append(p['id'])

lines = ["# skills-evidence-matrix.yaml — GENERATED by gen_matrix.py; do not hand-edit.",
         "# Regenerate after editing any skills[] field: python3 gen_matrix.py (from the repo root).",
         "# Skills with only publication evidence are still valid (publications count regardless of age),",
         "# but check whether an experience bullet would strengthen them.",
         "skills_evidence_matrix:"]
for s in sorted(matrix):
    e = matrix[s]
    lines.append(f"  {s}:")
    lines.append(f"    bullets: {e['bullets']}")
    lines.append(f"    publications: {e['publications']}")
open('skills-evidence-matrix.yaml', 'w').write("\n".join(lines) + "\n")

pub_only = [s for s, e in sorted(matrix.items()) if not e['bullets']]
print(f"roles: {len(bl.get('roles', {}))} | bullets: {len(all_bullets)} | pubs: {len(pl['publications'])} | skills: {len(matrix)}")
print("publication-only skills:", pub_only)
