#!/usr/bin/env python3
"""Regenerate skills-evidence-matrix.yaml from bullet-library.yaml + publication-library.yaml.
Run from the repo root after editing any skills[] field."""
import yaml

bl = yaml.safe_load(open('bullet-library.yaml'))   # role -> [bullets]
pl = yaml.safe_load(open('publication-library.yaml'))

matrix = {}
for role_bullets in bl.values():
    for b in role_bullets:
        for s in b['skills']:
            matrix.setdefault(s, {'bullets': [], 'publications': []})['bullets'].append(b['id'])
for p in pl['publications']:
    for s in p['skills']:
        matrix.setdefault(s, {'bullets': [], 'publications': []})['publications'].append(p['id'])

lines = ["# skills-evidence-matrix.yaml — GENERATED by gen_matrix.py; do not hand-edit.",
         "# Regenerate after editing any skills[] field: python3 gen_matrix.py (from the repo root).",
         "# Skills with only publication evidence are still valid (publications count regardless of age),",
         "# but check whether an experience bullet would strengthen them.",
         "skills_evidence_matrix:"]
for s in sorted(matrix):
    e = matrix[s]
    lines.append(f"  {s}:")
    lines.append(f"    bullets: {e['bullets']}")
    lines.append(f"    publications: {e['publications']}")
open('skills-evidence-matrix.yaml', 'w').write("\n".join(lines) + "\n")

n_bullets = sum(len(v) for v in bl.values())
pub_only = [s for s, e in sorted(matrix.items()) if not e['bullets']]
print(f"skills: {len(matrix)} | bullets: {n_bullets} | pubs: {len(pl['publications'])}")
print("publication-only skills:", pub_only)
